import type { VercelRequest, VercelResponse } from '@vercel/node'
import Busboy from 'busboy'
import { createClient, type SupabaseClient } from '@supabase/supabase-js'

const models = [
  { id: 'gpt-image-2', name: 'GPT Image 2', kind: 'image', available: true, description: 'Equilibrio entre detalle, velocidad y composición.', options: { size: ['1024x1024', '1536x1024', '1024x1536'], quality: ['standard', 'high'] } },
  { id: 'gpt-image-2-4k', name: 'GPT Image 2 · 4K', kind: 'image', available: true, description: 'Máxima resolución para piezas de alto detalle.', options: { size: ['2048x2048', '3840x2160'], quality: ['high'] } },
  { id: 'grok-imagine-image', name: 'Grok Imagine', kind: 'image', available: true, description: 'Dirección visual expresiva con resultados rápidos.', options: { size: ['1024x1024', '1536x1024', '1024x1536'], quality: ['standard'] } },
  { id: 'grok-imagine-image-quality', name: 'Grok Imagine Quality', kind: 'image', available: true, description: 'Mayor acabado para composiciones exigentes.', options: { size: ['1024x1024', '1536x1024', '1024x1536'], quality: ['high'] } },
  { id: 'deepseek-v4-flash-vision-exp', name: 'DeepSeek Vision', kind: 'vision', available: true, description: 'Analiza referencias para enriquecer el prompt.', options: {} },
]

const env = { supabaseUrl: process.env.SUPABASE_URL || '', anon: process.env.SUPABASE_ANON_KEY || '', service: process.env.SUPABASE_SERVICE_ROLE_KEY || '', cavotiKey: process.env.CAVOTI_API_KEY || '', cavotiBase: process.env.CAVOTI_BASE_URL || 'https://cavoti.com/v1' }
let admin: SupabaseClient | null = null
function db() { if (!admin && env.supabaseUrl && env.service) admin = createClient(env.supabaseUrl, env.service, { auth: { autoRefreshToken: false, persistSession: false } }); return admin }
function json(res: VercelResponse, status: number, payload: unknown) { res.status(status).setHeader('Content-Type', 'application/json').send(payload) }
function userId(req: VercelRequest) { const auth = req.headers.authorization; return auth?.startsWith('Bearer ') ? auth.slice(7) : null }
async function requireUser(req: VercelRequest, res: VercelResponse) { const token = userId(req); if (!token || !env.supabaseUrl || !env.anon) { json(res, 401, { detail: 'Sesión requerida.' }); return null } const client = createClient(env.supabaseUrl, env.anon, { auth: { autoRefreshToken: false, persistSession: false } }); const result = await client.auth.getUser(token); if (result.error || !result.data.user) { json(res, 401, { detail: 'Sesión de Supabase inválida.' }); return null } return result.data.user }
function decodeImage(value: string) { const bytes = Buffer.from(value, 'base64'); if (bytes.subarray(0, 8).toString('hex') !== '89504e470d0a1a0a') throw new Error('Cavoti devolvió una imagen inválida.'); return { bytes, width: bytes.readUInt32BE(16), height: bytes.readUInt32BE(20) } }
async function cavoti(path: string, payload: unknown) { if (!env.cavotiKey) throw new Error('CAVOTI_API_KEY no está configurada.'); const response = await fetch(`${env.cavotiBase.replace(/\/$/, '')}/${path}`, { method: 'POST', headers: { Authorization: `Bearer ${env.cavotiKey}`, 'Content-Type': 'application/json', Accept: 'application/json' }, body: JSON.stringify(payload) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error((data as any)?.error?.message || 'Cavoti rechazó la solicitud.'); return data as any }
async function signedUrl(path: string) { const client = db(); if (!client) return path; const result = await client.storage.from('generation-images').createSignedUrl(path, 3600); if (result.error) throw result.error; return result.data.signedUrl }
async function persistGeneration(user: string, request: any, result: any) { const client = db(); if (!client) return null; const id = crypto.randomUUID(); const images = []; for (const item of result.data || []) { if (!item.b64_json) continue; const decoded = decodeImage(item.b64_json); const imageId = crypto.randomUUID(); const path = `${user}/${imageId}.png`; const upload = await client.storage.from('generation-images').upload(path, decoded.bytes, { contentType: 'image/png', upsert: true }); if (upload.error) throw upload.error; images.push({ id: imageId, path, width: decoded.width, height: decoded.height }) } const row = await client.from('generations').insert({ id, user_id: user, prompt: request.prompt, model: request.model, options: { size: request.size, quality: request.quality, aspect_ratio: request.aspect_ratio, count: request.count }, revised_prompt: result.data?.[0]?.revised_prompt || null, status: 'completed' }).select().single(); if (row.error) throw row.error; const imageRows = images.map((item) => ({ id: item.id, generation_id: id, user_id: user, storage_path: item.path, width: item.width, height: item.height })); if (imageRows.length) { const inserted = await client.from('generation_images').insert(imageRows); if (inserted.error) throw inserted.error } return { id, images, revised_prompt: row.data.revised_prompt }
}
async function parseMultipart(req: VercelRequest): Promise<{ bytes: Buffer; mime: string }> { return new Promise((resolve, reject) => { const bb = Busboy({ headers: req.headers as Record<string, string> }); let bytes = Buffer.alloc(0); let mime = 'image/png'; bb.on('file', (_name, stream, info) => { mime = info.mimeType; stream.on('data', (chunk: Buffer) => { bytes = Buffer.concat([bytes, chunk]); if (bytes.length > 10 * 1024 * 1024) stream.destroy(new Error('La referencia no puede superar 10 MB.')) }); }); bb.on('finish', () => bytes.length ? resolve({ bytes, mime }) : reject(new Error('Debes subir una imagen.'))); bb.on('error', reject); req.pipe(bb) }) }

export async function handler(req: VercelRequest, res: VercelResponse) {
  const queryPath = req.query?.path
  const pathFromQuery = Array.isArray(queryPath) ? queryPath.join('/') : typeof queryPath === 'string' ? queryPath : ''
  const path = (pathFromQuery || (req.url || '').split('?')[0].replace(/^\/api\/?/, '').replace(/\/$/, '') || 'health').replace(/^index\/?/, '') || 'health'
  try {
    if (req.method === 'GET' && path === 'health') return json(res, 200, { status: 'ok', supabase_configured: Boolean(env.supabaseUrl && env.anon), cavoti_configured: Boolean(env.cavotiKey) })
    if (req.method === 'GET' && path === 'models') return json(res, 200, models)
    if (req.method === 'GET' && path === 'generations') { const user = await requireUser(req, res); if (!user) return; const client = db(); if (!client) return json(res, 200, []); const result = await client.from('generations').select('*,generation_images(*)').eq('user_id', user.id).order('created_at', { ascending: false }).limit(50); if (result.error) throw result.error; const output = await Promise.all((result.data || []).map(async (row: any) => ({ id: row.id, status: row.status, model: row.model, prompt: row.prompt, revised_prompt: row.revised_prompt, options: row.options || {}, created_at: row.created_at, images: await Promise.all((row.generation_images || []).map(async (image: any) => ({ id: image.id, url: await signedUrl(image.storage_path), width: image.width, height: image.height }))) }))); return json(res, 200, output) }
    if (req.method === 'POST' && path === 'references/analyze') { const user = await requireUser(req, res); if (!user) return; const image = await parseMultipart(req); if (!['image/png', 'image/jpeg', 'image/webp'].includes(image.mime)) return json(res, 415, { detail: 'Usa una imagen PNG, JPG o WebP.' }); const encoded = image.bytes.toString('base64'); const result = await cavoti('chat/completions', { model: 'deepseek-v4-flash-vision-exp', messages: [{ role: 'user', content: [{ type: 'text', text: 'Describe la imagen con precisión para usarla como referencia de generación. Enfócate en sujeto, composición, iluminación, materiales, colores y estilo. Responde en español, en un solo bloque.' }, { type: 'image_url', image_url: { url: `data:${image.mime};base64,${encoded}` } }] }], max_tokens: 500 }); return json(res, 200, { analysis: result.choices?.[0]?.message?.content || '', model: 'deepseek-v4-flash-vision-exp' }) }
    if (req.method === 'POST' && path === 'generations') { const user = await requireUser(req, res); if (!user) return; const request = typeof req.body === 'string' ? JSON.parse(req.body) : req.body; const model = models.find((item) => item.id === request.model && item.kind === 'image'); if (!model) return json(res, 400, { detail: 'Selecciona un modelo de generación válido.' }); const supportedSizes = model.options.size || []; if (!supportedSizes.includes(request.size)) return json(res, 400, { detail: 'La resolución no es compatible con este modelo.' }); const prompt = request.reference_analysis ? `${request.prompt}\n\nReferencia visual analizada:\n${request.reference_analysis}` : request.prompt; const result = await cavoti('images/generations', { model: request.model, prompt, size: request.size, quality: request.quality, n: Math.min(Number(request.count) || 1, 4), response_format: 'b64_json' }); const persisted = await persistGeneration(user.id, request, result); const images = await Promise.all((persisted?.images || []).map(async (item: any) => ({ id: item.id, url: await signedUrl(item.path), width: item.width, height: item.height }))); return json(res, 200, { id: persisted?.id || crypto.randomUUID(), status: 'completed', model: request.model, prompt: request.prompt, revised_prompt: persisted?.revised_prompt || result.data?.[0]?.revised_prompt || null, images, options: { size: request.size, quality: request.quality, aspect_ratio: request.aspect_ratio, count: request.count }, created_at: new Date().toISOString() }) }
    const deleteMatch = path.match(/^generations\/([^/]+)$/); if (req.method === 'DELETE' && deleteMatch) { const user = await requireUser(req, res); if (!user) return; const client = db(); if (!client) return res.status(204).end(); const rows = await client.from('generation_images').select('storage_path').eq('generation_id', deleteMatch[1]).eq('user_id', user.id); if (rows.error) throw rows.error; const paths = (rows.data || []).map((row: any) => row.storage_path); if (paths.length) await client.storage.from('generation-images').remove(paths); const deleted = await client.from('generations').delete().eq('id', deleteMatch[1]).eq('user_id', user.id); if (deleted.error) throw deleted.error; return res.status(204).end() }
    return json(res, 404, { detail: 'Ruta no encontrada.' })
  } catch (error) { console.error('KloweRG API error:', error instanceof Error ? error.message : error); return json(res, 502, { detail: error instanceof Error ? error.message : 'Error inesperado.' }) }
}
